# Generated by Django 4.0.4 on 2022-06-29 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name_tr', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name_tr', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('exam_capacity', models.IntegerField(null=True)),
                ('obs_code', models.CharField(max_length=255, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.building')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=255, null=True)),
                ('course_name_tr', models.CharField(max_length=255, null=True)),
                ('course_name_en', models.CharField(max_length=255, null=True)),
                ('credit_t', models.IntegerField(null=True)),
                ('credit_u', models.IntegerField(null=True)),
                ('credit_ects', models.IntegerField(null=True)),
                ('semester', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('day_tr', models.CharField(max_length=15, null=True)),
                ('day_en', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Open_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('num_students', models.IntegerField(null=True)),
                ('division', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.course')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title_tr', models.CharField(max_length=255)),
                ('short_title_tr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('short_title_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('role_tr', models.CharField(max_length=255, null=True)),
                ('role_en', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=255, null=True)),
                ('semesters', models.CharField(max_length=255, null=True)),
                ('semester', models.IntegerField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title_tr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title_tr', models.CharField(max_length=255)),
                ('short_title_tr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('short_title_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weekly_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('start', models.TimeField(default=datetime.time(0, 0))),
                ('end', models.TimeField(default=datetime.time(0, 0))),
                ('lesson_duration', models.IntegerField(null=True)),
                ('lesson_break', models.IntegerField(null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.building')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.classroom')),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.day')),
                ('open_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.open_course')),
            ],
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('programs_id', models.ManyToManyField(to='DersTakip.program')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.role')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.unit')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.unit'),
        ),
        migrations.AddField(
            model_name='open_course',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.semester'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.title'),
        ),
        migrations.AddField(
            model_name='course',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DersTakip.program'),
        ),
    ]
