# Generated by Django 4.0.4 on 2022-06-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DersTakip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_program',
            name='program_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DersTakip.program'),
            preserve_default=False,
        ),
    ]
