from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name="index"),
    path('indexadmin',views.indexadmin,name="indexadmin"),
    path('bolumler',views.bolumler,name="bolumler"),
    path('dersler',views.dersler,name="dersler"),
    path('acilandersler',views.acilandersler,name="acilandersler"),
    path('haftalikprogram',views.haftalikprogram,name="haftalıkprogram"),
    path('dersekle',views.dersekle,name="dersekle"),
    path('dersduzenle/<int:id>',views.dersduzenle,name="dersduzenle"),
    path('derssil/<int:id>',views.derssil,name="derssil"),
    path('bolumekle',views.bolumekle,name="bolumekle"),
    path('bolumduzenle/<int:id>',views.bolumduzenle,name="bolumduzenle"),
    path('bolumsil/<int:id>', views.bolumsil, name="bolumsil"),
    path('acilandersekle', views.acilandersekle, name="acilandersekle"),
    path('acilandersduzenle/<int:id>', views.acilandersduzenle, name="acilandersduzenle"),
    path('acilanderssil/<int:id>', views.acilanderssil, name="acilanderssil"),
    path('haftalikprogramekle', views.haftalikprogramekle, name="haftalikprogramekle"),
    path('haftalikprogramduzenle/<int:id>', views.haftalikprogramduzenle, name="haftalikprogramduzenle"),
    path('haftalikprogramsil/<int:id>', views.haftalikprogramsil, name="haftalikprogramsil"),
    path('yerleske', views.yerleske, name="yerleske"),
    path('yerleskeekle', views.yerleskeekle, name="yerleskeekle"),
    path('yerleskeduzenle/<int:id>', views.yerleskeduzenle, name="yerleskeduzenle"),
    path('yerleskesil/<int:id>', views.yerleskesil, name="yerleskesil"),
    path('sinif', views.sinif, name="sinif"),
    path('sinifekle', views.sinifekle, name="sinifekle"),
    path('sinifduzenle/<int:id>', views.sinifduzenle, name="sinifduzenle"),
    path('sinifsil/<int:id>', views.sinifsil, name="sinifsil"),
    path('hoca', views.hoca, name="hoca"),
    path('hocaekle', views.hocaekle, name="hocaekle"),
    path('hocaduzenle/<int:id>', views.hocaduzenle, name="hocaduzenle"),
    path('hocasil/<int:id>', views.hocasil, name="hocasil"),
    path('bolumadmin', views.bolumadmin, name="bolumadmin"),
    path('bolumadminekle', views.bolumadminekle, name="bolumadminekle"),
    path('bolumadminduzenle/<int:id>', views.bolumadminduzenle, name="bolumadminduzenle"),
    path('bolumadminsil/<int:id>', views.bolumadminsil, name="bolumadminsil"),
    path('dersadmin', views.dersadmin, name="dersadmin"),
    path('dersadminekle', views.dersadminekle, name="dersadminekle"),
    path('dersadminduzenle/<int:id>', views.dersadminduzenle, name="dersadminduzenle"),
    path('dersadminsil/<int:id>', views.dersadminsil, name="dersadminsil"),
    path('acilandersleradmin', views.acilandersleradmin, name="acilandersleradmin"),
    path('acilandersadminekle', views.acilandersadminekle, name="acilandersadminekle"),
    path('acilandersadminduzenle/<int:id>', views.acilandersadminduzenle, name="acilandersadminduzenle"),
    path('acilandersadminsil/<int:id>', views.acilandersadminsil, name="acilandersadminsil"),

]